AWSTemplateFormatVersion: "2010-09-09"
Description: This is a CFN template to create VPCs for Lab 5.
Parameters:
  User:
    Type: String
  Name:
    Type: String
  InstanceType:
    Type: String
  KeyPair:
    Description: Key Value Pair
    Type: String
    Default: "paschalonor"
  LinuxAMI:
    Type: AWS::EC2::Image::Id
  WindowsAMI:
    Type: AWS::EC2::Image::Id

Resources:
  LaunchTemplate:
     Type: AWS::EC2::LaunchTemplate
     Properties: 
       LaunchTemplateData: 
         InstanceType: !Ref InstanceType
         KeyName: !Ref KeyPair
         TagSpecifications: 
           - ResourceType: instance
             Tags: 
               - Key: user
                 Value: !Ref User
               - Key: Name
                 Value: !Ref Name
       LaunchTemplateName: !Ref User
       TagSpecifications: 
         - ResourceType: launch-template
           Tags: 
             - Key: user
               Value: !Ref User
            #  - Key: Name
            #    Value: !Ref User 
  FirstEc2:
     Type: AWS::EC2::Instance
     Properties: 
       ImageId: !Ref LinuxAMI
       LaunchTemplate: 
         LaunchTemplateId: !Ref LaunchTemplate
         Version: 1

  SecondEc2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId:  !Ref WindowsAMI
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
    

Outputs: #The Launch Template 
  LaunchTemplate:
    Description: The Launch Template
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub "${AWS::StackName}-LaunchTemplate"

  FirstEc2:
    Description: The ID of the 1st Instance
    Value: !Ref FirstEc2
    Export:
      Name: !Sub "${AWS::StackName}-FirstEc2"

  SecondEc2:
    Description: The ID of the 2nd Instance
    Value: !Ref SecondEc2
    Export:
      Name: !Sub "${AWS::StackName}-SecondEc2"