AWSTemplateFormatVersion: "2010-09-09"
Description: This is a CFN template to create EC2 for Lab 5.

Parameters:
  User:
    Type: String
  InstanceType:
    Type: String
  KeyPair:
    Description: Key Value Pair
    Type: String
    Default: "paschalonor"
  LinuxAMI:
    Type: AWS::EC2::Image::Id
  SSHLocation:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP address range that can be used to access the web server using SSH.
    MaxLength: '18'
    MinLength: '9'
    Type: String


Resources:
  LaunchTemplate:
     Type: AWS::EC2::LaunchTemplate
     Properties: 
       LaunchTemplateData: 
         InstanceType: !Ref InstanceType
         KeyName: !Ref KeyPair
         SecurityGroupIds: 
           - !GetAtt  SSHSecurityGroup.GroupId
         UserData:
           Fn::Base64: !Sub |
             #!/bin/bash
             wget https://s3.us-east-1.amazonaws.com/amazoncloudwatch-agent-us-east-1/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
             dpkg -i -E ./amazon-cloudwatch-agent.deb
             echo """
             {
               "agent": {
                 "metrics_collection_interval": 10,
                 "run_as_user": "cwagent",
                 "region": "us-east-1"
               },
               "metrics": {
                 "metrics_collected": {
                   "cpu": {
                     "resources": [
                       "*"
                     ],
                     "measurement": [
                       {"name": "cpu_usage_idle", "rename": "CPU_USAGE_IDLE", "unit": "Percent"},
                       {"name": "cpu_usage_nice", "unit": "Percent"},
                       "cpu_usage_guest"
                     ],
                     "totalcpu": false,
                     "metrics_collection_interval": 10
                   },
                   "collectd": {
                     "metrics_aggregation_interval": 10
                   },
                   "disk": {
                     "measurement": [
                       "used_percent"
                     ],
                     "metrics_collection_interval": 10,
                     "resources": [
                       "*"
                     ]
                   },
                   "mem": {
                     "measurement": [
                       "mem_used_percent"
                     ],
                     "metrics_collection_interval": 10
                   },
                   "statsd": {
                     "metrics_aggregation_interval": 10,
                     "metrics_collection_interval": 10,
                     "service_address": ":8125"
                   }
                 }
               }
             }

             """ > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
             /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a start
             /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status
         IamInstanceProfile:
           Name: !Ref InstanceProfile
         TagSpecifications: 
           - ResourceType: instance
             Tags: 
               - Key: user
                 Value: !Ref User
       
       LaunchTemplateName: !Ref User
       TagSpecifications: 
         - ResourceType: launch-template
           Tags: 
             - Key: user
               Value: !Ref User
      


  FirstEc2:
     Type: AWS::EC2::Instance
     Properties: 
       ImageId: !Ref LinuxAMI
       LaunchTemplate: 
         LaunchTemplateId: !Ref LaunchTemplate
         Version: 1
    # DependsOn: SSHSecurityGroup

  MyEIP:
     Type: AWS::EC2::EIP
     Properties: 
       InstanceId: !Ref FirstEc2
       Tags: 
         - Key: user
           Value: !Ref User

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation
      - IpProtocol: icmp
        FromPort: 8
        ToPort: -1
        CidrIp: !Ref SSHLocation

  Role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: !Ref User
      Policies: 
        - PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - cloudwatch:PutMetricData
                - ec2:DescribeVolumes
                - ec2:DescribeTags
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*
          PolicyName: !Ref User
      RoleName: !Ref User
      Tags:   
        - Key: user
          Value: !Ref User

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Ref User
      Roles: 
        - !Ref Role



Outputs:
  MyEIP:
    Description: My Elastic IP 
    Value: !Ref MyEIP
    Export:
      Name: !Sub "${AWS::StackName}-MyEIP"