AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcCidr:
    Description: Please enter the IP Range (CIDR Notation) for this private subnet
    Type: String
  PrivateSubnetCidr:
    # Default: 10.0.0.0/24
    Description: Please enter the IP Range (CIDR Notation) for this private subnet
    Type: String

Resources:
  PaschalVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      # Ipv4IpamPoolId: 
      # Ipv4NetmaskLength: 
      Tags: 
        - Key: User
          Value: paschal.onor.labs
  myPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PaschalVPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
      - Key: User
        Value: paschal.onor.labs Private Subnet 1

Outputs:
  OutputForPaschalVPCId:
    Description: "Paschal VPC"
    Value: !Ref PaschalVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  OutputFormyPrivateSubnetId:
    Description: "my Private Subnet"
    Value: !Ref myPrivateSubnet
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet"