AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  User:
    Type: String
  Lab:
    Type: String

Resources:
  myMainKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An example symmetric KMS key
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::324320755747:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::324320755747:user/paschal.onor.labs'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::324320755747:user/paschal.onor.labs'
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'
      Tags: 
        - Key: user
          Value: !Ref User
        - Key: Name
          Value: !Ref User
        - Key: stelligent-u-lab
          Value: !Ref Lab

  myAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/exampleAlias
      TargetKeyId: !Ref myMainKey