AWSTemplateFormatVersion: "2010-09-09"
Resources:
  iamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: myUser

  iamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: paschal-012-iampolicy
      Users:
       - !Ref iamUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:Get*"
            Resource: "*"