AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  S3BucketName:
    Description: Bucket name
    Type: String
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Ref S3BucketName
