# 3.1.1
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'Password'
      UserName: "Paschal"
  CFNUserRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - "iam.amazonaws.com"
              AWS:
                - !Ref CFNUser
            Action:
              - 'sts:AssumeRole'
      Path: "/"
  CFNUserPolicies:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "CFNUsers"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['iam:List*', 'iam:Get*', 'iam:Generate*']
          Resource: '*'
      Users:
        - !Ref CFNUser

