AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CFNUserRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - "iam.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
  
  Ec2Role: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess