AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  iamUser:
    Description: IAM UserName
    Type: String
Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - "iam.amazonaws.com"
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/${iamUser}"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: iamViewPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'iam:List*'
                  - 'iam:Get*'
                  - 'iam:Generate*'
                Resource: '*'
          # Users:
          #   - !Sub "arn:aws:iam::${AWS::AccountId}:user/${iamUser}"     
  # RootInstanceProfile:
  #   Type: 'AWS::IAM::InstanceProfile'
  #   Properties:
  #     Path: /
  #     Roles:
  #       - !Ref RootRole